#!/usr/bin/env python
if __name__ == '__main__':
	import gevent.monkey, logging
	import argparse

	from xmpp_to_tlen.listener import Listener

	parser = argparse.ArgumentParser()
	parser.add_argument('--debug', dest='debug', action='store_true',
		help='Show debugging output')
	parser.add_argument('-p', '--port', dest='listen_port', type=int,
		default=5222, help='Listen port for incoming XMPP connections.')

	args = parser.parse_args()

	gevent.monkey.patch_all()

	logging.basicConfig()
	if args.debug:
		logging.getLogger('xmpp_to_tlen').setLevel(logging.DEBUG)
		logging.getLogger('pyxmpp2.IN').setLevel(logging.DEBUG)
		logging.getLogger('pyxmpp2.OUT').setLevel(logging.DEBUG)

	listener = Listener(port=args.listen_port)

	print 'xmpp-to-tlen accepting connections at 127.0.0.1:%i' % (args.listen_port, )
	listener.serve()

